#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true
org.jetbrains.compose.experimental.jscanvas.enabled=true

kotlin.js.compiler=ir
kotlin.js.yarn.lock-mismatch-report=WARNING
kotlin.js.yarn.lock-update=true